INSERT INTO dn_dict.df_drone_state( state_id, code, description, name ) VALUES ( 1, 'IDLE', 'IDLE', 'IDLE');
INSERT INTO dn_dict.df_drone_state( state_id, code, description, name ) VALUES ( 2, 'LOADING', 'LOADING', 'LOADING');
INSERT INTO dn_dict.df_drone_state( state_id, code, description, name ) VALUES ( 3, 'LOADED', 'LOADED', 'LOADED');
INSERT INTO dn_dict.df_drone_state( state_id, code, description, name ) VALUES ( 4, 'DELIVERING', 'DELIVERING', 'DELIVERING');
INSERT INTO dn_dict.df_drone_state( state_id, code, description, name ) VALUES ( 5, 'DELIVERED', 'DELIVERED', 'DELIVERED');
INSERT INTO dn_dict.df_drone_state( state_id, code, description, name ) VALUES ( 6, 'RETURNING', 'RETURNING', 'RETURNING');
INSERT INTO dn_dict.df_load_model( model_id, code, description, name ) VALUES ( 1, 'Lightweight', 'Lightweight', 'Lightweight');
INSERT INTO dn_dict.df_load_model( model_id, code, description, name ) VALUES ( 2, 'Middleweight', 'Middleweight', 'Middleweight');
INSERT INTO dn_dict.df_load_model( model_id, code, description, name ) VALUES ( 3, 'Cruiserweight', 'Cruiserweight', 'Cruiserweight');
INSERT INTO dn_dict.df_load_model( model_id, code, description, name ) VALUES ( 4, 'Heavyweight', 'Heavyweight', 'Heavyweight');
INSERT INTO dn_dict.df_load_type( load_type_id, code, description, name ) VALUES ( 1, 'MEDICATION', 'Medication', 'Medication');
INSERT INTO dn_dict.df_office( office_id, active, code, email, fax, head_name, name, office_phone, postal_address, street_address, web_site ) VALUES ( 1, true, 'ubmal_pleven_hospital', null, null, null, 'Ubmal Pleven Hospital', null, null, null, null);
INSERT INTO dn_dict.df_station( station_id, code, description, latitude, longitude, name ) VALUES ( 1, 'kula_hospital', 'Kula Municipality Hospital', 43.8897, 22.5193, 'Kula Municipality Hospital');
INSERT INTO dn_dict.df_trip_status( status_id, code, description, name ) VALUES ( 1, 'SCHEDULED', 'SCHEDULED', 'SCHEDULED');
INSERT INTO dn_dict.df_trip_status( status_id, code, description, name ) VALUES ( 2, 'DELIVERING', 'DELIVERING', 'DELIVERING');
INSERT INTO dn_dict.df_trip_status( status_id, code, description, name ) VALUES ( 3, 'RETURNING', 'RETURNING', 'RETURNING');
INSERT INTO dn_dict.df_trip_status( status_id, code, description, name ) VALUES ( 4, 'COMPLETED', 'COMPLETED', 'COMPLETED');
INSERT INTO dn_main.dm_approle( role_id, description, role_code, role_name ) VALUES ( 1, 'Administrator', 'ROLE_Admin', 'Admin');
INSERT INTO dn_main.dm_appuser( user_id, enabled, acc_exp_date, acc_not_locked, creation_date, cred_exp_date, email, first_name, gender, inactivation_date, initials, job_title, last_name, password, second_name, user_name, uuid, assignee_user_id, office_id ) VALUES ( 1, true, null, true, null, null, 'georgejbudeba@gmail.com', 'Musala', null, null, null, null, 'Soft', '$2a$10$GRVLk1.cqICCDKONI94AGe1v5hl4Znsu9CUgUy28c9UEBzEI60DGK', null, 'musala', null, null, 1);
INSERT INTO dn_main.dm_user_permission( user_id, role_id ) VALUES ( 1, 1);