-- H2 2.1.214;
;             
CREATE USER IF NOT EXISTS "MUSALA" SALT '75f94a486f4f60b9' HASH '9985067ce2db30bf698b1873757d0d81484aff9bd22facc7321a6a1dc0cf2058' ADMIN;     
CREATE SCHEMA IF NOT EXISTS "DN_DICT" AUTHORIZATION "MUSALA"; 
CREATE SCHEMA IF NOT EXISTS "DN_AUD" AUTHORIZATION "MUSALA";  
CREATE SCHEMA IF NOT EXISTS "DN_MAIN" AUTHORIZATION "MUSALA"; 
DROP SEQUENCE IF EXISTS "PUBLIC"."HIBERNATE_SEQUENCE";
CREATE MEMORY TABLE  IF NOT EXISTS"DN_AUD"."AUD_APPROLE"(
    "ROLE_ID" INTEGER NOT NULL,
    "REV" BIGINT NOT NULL,
    "REVTYPE" TINYINT,
    "DESCRIPTION" CHARACTER VARYING(200),
    "ROLE_CODE" CHARACTER VARYING(100),
    "ROLE_NAME" CHARACTER VARYING(100)
);              
ALTER TABLE "DN_AUD"."AUD_APPROLE" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."CONSTRAINT_D" PRIMARY KEY("ROLE_ID", "REV");      
-- 0 +/- SELECT COUNT(*) FROM DN_AUD.AUD_APPROLE;             
CREATE MEMORY TABLE  IF NOT EXISTS"DN_AUD"."AUD_APPUSER"(
    "USER_ID" BIGINT NOT NULL,
    "REV" BIGINT NOT NULL,
    "REVTYPE" TINYINT,
    "ENABLED" BOOLEAN,
    "ACC_EXP_DATE" TIMESTAMP,
    "ACC_NOT_LOCKED" BOOLEAN,
    "CREATION_DATE" TIMESTAMP,
    "CRED_EXP_DATE" TIMESTAMP,
    "EMAIL" CHARACTER VARYING(100),
    "FIRST_NAME" CHARACTER VARYING(100),
    "GENDER" CHARACTER VARYING(100),
    "INACTIVATION_DATE" TIMESTAMP,
    "INITIALS" CHARACTER VARYING(100),
    "JOB_TITLE" CHARACTER VARYING(100),
    "LAST_NAME" CHARACTER VARYING(100),
    "PASSWORD" CHARACTER VARYING(100),
    "SECOND_NAME" CHARACTER VARYING(100),
    "USER_NAME" CHARACTER VARYING(100),
    "UUID" CHARACTER VARYING(70),
    "ASSIGNEE_USER_ID" BIGINT,
    "OFFICE_ID" BIGINT
);           
ALTER TABLE "DN_AUD"."AUD_APPUSER" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."CONSTRAINT_D4" PRIMARY KEY("USER_ID", "REV");     
-- 0 +/- SELECT COUNT(*) FROM DN_AUD.AUD_APPUSER;             
CREATE MEMORY TABLE  IF NOT EXISTS"DN_AUD"."AUD_DRONE"(
    "DRONE_ID" BIGINT NOT NULL,
    "REV" BIGINT NOT NULL,
    "REVTYPE" TINYINT,
    "BATTERY_CAPACIT" NUMERIC(4, 2),
    "SERIAL_NUMBER" CHARACTER VARYING(255),
    "WEIGHT" NUMERIC(7, 4),
    "MODEL_ID" INTEGER,
    "STATE_ID" INTEGER
);           
ALTER TABLE "DN_AUD"."AUD_DRONE" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."CONSTRAINT_D6" PRIMARY KEY("DRONE_ID", "REV");      
-- 0 +/- SELECT COUNT(*) FROM DN_AUD.AUD_DRONE;               
CREATE MEMORY TABLE  IF NOT EXISTS"DN_AUD"."AUD_ITEM"(
    "ITEM_ID" INTEGER NOT NULL,
    "REV" BIGINT NOT NULL,
    "REVTYPE" TINYINT,
    "CODE" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING,
    "NAME" CHARACTER VARYING(255),
    "LOAD_ID" BIGINT
);         
ALTER TABLE "DN_AUD"."AUD_ITEM" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."CONSTRAINT_6" PRIMARY KEY("ITEM_ID", "REV");         
-- 0 +/- SELECT COUNT(*) FROM DN_AUD.AUD_ITEM;
CREATE MEMORY TABLE  IF NOT EXISTS"DN_AUD"."AUD_LOAD"(
    "LOAD_ID" BIGINT NOT NULL,
    "REV" BIGINT NOT NULL,
    "REVTYPE" TINYINT,
    "CODE" CHARACTER VARYING(255),
    "IMAGE" BINARY LARGE OBJECT,
    "NAME" CHARACTER VARYING(255),
    "WEIGHT" NUMERIC(12, 4),
    "TRIP_ID" BIGINT,
    "LOAD_TYPE_ID" INTEGER
);   
ALTER TABLE "DN_AUD"."AUD_LOAD" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."CONSTRAINT_6A" PRIMARY KEY("LOAD_ID", "REV");        
-- 0 +/- SELECT COUNT(*) FROM DN_AUD.AUD_LOAD;
CREATE MEMORY TABLE  IF NOT EXISTS"DN_AUD"."AUD_REVISION"(
    "REV" BIGINT NOT NULL,
    "SOURCE" CHARACTER VARYING(20),
    "TIMESTAMP" BIGINT,
    "PRINCIPAL" CHARACTER VARYING(50)
);             
ALTER TABLE "DN_AUD"."AUD_REVISION" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."CONSTRAINT_6C" PRIMARY KEY("REV");               
-- 0 +/- SELECT COUNT(*) FROM DN_AUD.AUD_REVISION;            
CREATE MEMORY TABLE  IF NOT EXISTS"DN_AUD"."AUD_TRIP"(
    "TRIP_ID" BIGINT NOT NULL,
    "REV" BIGINT NOT NULL,
    "REVTYPE" TINYINT,
    "ARRIVE_DATETIME" TIMESTAMP,
    "DEPARTURE_DATETIME" TIMESTAMP,
    "DISTACE" NUMERIC(12, 4),
    "RETURN_DATETIME" TIMESTAMP,
    "STATION_ID" INTEGER,
    "DRONE_ID" BIGINT,
    "OFFICE_ID" INTEGER,
    "STATUS_ID" INTEGER
);
ALTER TABLE "DN_AUD"."AUD_TRIP" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."CONSTRAINT_6A0" PRIMARY KEY("TRIP_ID", "REV");       
-- 0 +/- SELECT COUNT(*) FROM DN_AUD.AUD_TRIP;
CREATE MEMORY TABLE  IF NOT EXISTS"DN_DICT"."DF_DRONE_STATE"(
    "STATE_ID" INTEGER NOT NULL,
    "CODE" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING,
    "NAME" CHARACTER VARYING(255)
);            
ALTER TABLE "DN_DICT"."DF_DRONE_STATE" ADD CONSTRAINT IF NOT EXISTS "DN_DICT"."CONSTRAINT_2" PRIMARY KEY("STATE_ID");       
-- 6 +/- SELECT COUNT(*) FROM DN_DICT.DF_DRONE_STATE;         
     
CREATE MEMORY TABLE  IF NOT EXISTS"DN_DICT"."DF_LOAD_MODEL"(
    "MODEL_ID" INTEGER NOT NULL,
    "CODE" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING,
    "NAME" CHARACTER VARYING(255)
);             
ALTER TABLE "DN_DICT"."DF_LOAD_MODEL" ADD CONSTRAINT IF NOT EXISTS "DN_DICT"."CONSTRAINT_1" PRIMARY KEY("MODEL_ID");        
-- 4 +/- SELECT COUNT(*) FROM DN_DICT.DF_LOAD_MODEL;          

CREATE MEMORY TABLE  IF NOT EXISTS"DN_DICT"."DF_LOAD_TYPE"(
    "LOAD_TYPE_ID" INTEGER NOT NULL,
    "CODE" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING,
    "NAME" CHARACTER VARYING(255)
);          
ALTER TABLE "DN_DICT"."DF_LOAD_TYPE" ADD CONSTRAINT IF NOT EXISTS "DN_DICT"."CONSTRAINT_6" PRIMARY KEY("LOAD_TYPE_ID");     
-- 1 +/- SELECT COUNT(*) FROM DN_DICT.DF_LOAD_TYPE;           
CREATE MEMORY TABLE  IF NOT EXISTS"DN_DICT"."DF_OFFICE"(
    "OFFICE_ID" BIGINT NOT NULL,
    "ACTIVE" BOOLEAN,
    "CODE" CHARACTER VARYING(100),
    "EMAIL" CHARACTER VARYING(100),
    "FAX" CHARACTER VARYING(100),
    "HEAD_NAME" CHARACTER VARYING(100),
    "NAME" CHARACTER VARYING(100),
    "OFFICE_PHONE" CHARACTER VARYING(100),
    "POSTAL_ADDRESS" CHARACTER VARYING(100),
    "STREET_ADDRESS" CHARACTER VARYING(100),
    "WEB_SITE" CHARACTER VARYING(100)
);               
ALTER TABLE "DN_DICT"."DF_OFFICE" ADD CONSTRAINT IF NOT EXISTS "DN_DICT"."CONSTRAINT_F" PRIMARY KEY("OFFICE_ID");           
-- 1 +/- SELECT COUNT(*) FROM DN_DICT.DF_OFFICE;              
CREATE MEMORY TABLE  IF NOT EXISTS"DN_DICT"."DF_STATION"(
    "STATION_ID" INTEGER NOT NULL,
    "CODE" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING,
    "LATITUDE" DOUBLE PRECISION,
    "LONGITUDE" DOUBLE PRECISION,
    "NAME" CHARACTER VARYING(255)
);         
ALTER TABLE "DN_DICT"."DF_STATION" ADD CONSTRAINT IF NOT EXISTS "DN_DICT"."CONSTRAINT_B" PRIMARY KEY("STATION_ID");         
-- 1 +/- SELECT COUNT(*) FROM DN_DICT.DF_STATION;             
CREATE MEMORY TABLE  IF NOT EXISTS"DN_DICT"."DF_TRIP_STATUS"(
    "STATUS_ID" INTEGER NOT NULL,
    "CODE" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING,
    "NAME" CHARACTER VARYING(255)
);           
ALTER TABLE "DN_DICT"."DF_TRIP_STATUS" ADD CONSTRAINT IF NOT EXISTS "DN_DICT"."CONSTRAINT_1D" PRIMARY KEY("STATUS_ID");     
-- 4 +/- SELECT COUNT(*) FROM DN_DICT.DF_TRIP_STATUS;         
     
CREATE MEMORY TABLE  IF NOT EXISTS"DN_MAIN"."DM_APPROLE"(
    "ROLE_ID" INTEGER NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(200),
    "ROLE_CODE" CHARACTER VARYING(100),
    "ROLE_NAME" CHARACTER VARYING(100)
);  
ALTER TABLE "DN_MAIN"."DM_APPROLE" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."CONSTRAINT_4" PRIMARY KEY("ROLE_ID");            
-- 1 +/- SELECT COUNT(*) FROM DN_MAIN.DM_APPROLE;             
CREATE MEMORY TABLE  IF NOT EXISTS"DN_MAIN"."DM_APPUSER"(
    "USER_ID" BIGINT NOT NULL,
    "ENABLED" BOOLEAN,
    "ACC_EXP_DATE" TIMESTAMP,
    "ACC_NOT_LOCKED" BOOLEAN,
    "CREATION_DATE" TIMESTAMP,
    "CRED_EXP_DATE" TIMESTAMP,
    "EMAIL" CHARACTER VARYING(100),
    "FIRST_NAME" CHARACTER VARYING(100),
    "GENDER" CHARACTER VARYING(100),
    "INACTIVATION_DATE" TIMESTAMP,
    "INITIALS" CHARACTER VARYING(100),
    "JOB_TITLE" CHARACTER VARYING(100),
    "LAST_NAME" CHARACTER VARYING(100),
    "PASSWORD" CHARACTER VARYING(100),
    "SECOND_NAME" CHARACTER VARYING(100),
    "USER_NAME" CHARACTER VARYING(100),
    "UUID" CHARACTER VARYING(70),
    "ASSIGNEE_USER_ID" BIGINT,
    "OFFICE_ID" BIGINT
);               
ALTER TABLE "DN_MAIN"."DM_APPUSER" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."CONSTRAINT_42" PRIMARY KEY("USER_ID");           
-- 1 +/- SELECT COUNT(*) FROM DN_MAIN.DM_APPUSER;             
CREATE MEMORY TABLE  IF NOT EXISTS"DN_MAIN"."DM_DRONE"(
    "DRONE_ID" BIGINT NOT NULL,
    "BATTERY_CAPACIT" NUMERIC(4, 2),
    "SERIAL_NUMBER" CHARACTER VARYING(255),
    "WEIGHT" NUMERIC(7, 4),
    "MODEL_ID" INTEGER,
    "STATE_ID" INTEGER
);               
ALTER TABLE "DN_MAIN"."DM_DRONE" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."CONSTRAINT_2" PRIMARY KEY("DRONE_ID");             
-- 0 +/- SELECT COUNT(*) FROM DN_MAIN.DM_DRONE;               
CREATE MEMORY TABLE  IF NOT EXISTS"DN_MAIN"."DM_ITEM"(
    "ITEM_ID" INTEGER NOT NULL,
    "CODE" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING,
    "NAME" CHARACTER VARYING(255),
    "LOAD_ID" BIGINT
);             
ALTER TABLE "DN_MAIN"."DM_ITEM" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."CONSTRAINT_9" PRIMARY KEY("ITEM_ID");               
-- 0 +/- SELECT COUNT(*) FROM DN_MAIN.DM_ITEM;
CREATE MEMORY TABLE  IF NOT EXISTS"DN_MAIN"."DM_LOAD"(
    "LOAD_ID" BIGINT NOT NULL,
    "CODE" CHARACTER VARYING(255),
    "IMAGE" BINARY LARGE OBJECT,
    "NAME" CHARACTER VARYING(255),
    "WEIGHT" NUMERIC(12, 4),
    "TRIP_ID" BIGINT,
    "LOAD_TYPE_ID" INTEGER
);       
ALTER TABLE "DN_MAIN"."DM_LOAD" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."CONSTRAINT_95" PRIMARY KEY("LOAD_ID");              
-- 0 +/- SELECT COUNT(*) FROM DN_MAIN.DM_LOAD;
CREATE MEMORY TABLE  IF NOT EXISTS"DN_MAIN"."DM_TRIP"(
    "TRIP_ID" BIGINT NOT NULL,
    "ARRIVE_DATETIME" TIMESTAMP,
    "DEPARTURE_DATETIME" TIMESTAMP,
    "DISTACE" NUMERIC(12, 4),
    "RETURN_DATETIME" TIMESTAMP,
    "STATION_ID" INTEGER,
    "DRONE_ID" BIGINT,
    "OFFICE_ID" INTEGER,
    "STATUS_ID" INTEGER
);    
ALTER TABLE "DN_MAIN"."DM_TRIP" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."CONSTRAINT_95E" PRIMARY KEY("TRIP_ID");             
-- 0 +/- SELECT COUNT(*) FROM DN_MAIN.DM_TRIP;
CREATE MEMORY TABLE  IF NOT EXISTS"DN_MAIN"."DM_USER_PERMISSION"(
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" INTEGER NOT NULL
);       
ALTER TABLE "DN_MAIN"."DM_USER_PERMISSION" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."CONSTRAINT_3" PRIMARY KEY("USER_ID", "ROLE_ID");         
-- 1 +/- SELECT COUNT(*) FROM DN_MAIN.DM_USER_PERMISSION;     
ALTER TABLE "DN_AUD"."AUD_TRIP" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."FKNCWSJMT24B45867P4OPWI4XU9" FOREIGN KEY("REV") REFERENCES "DN_AUD"."AUD_REVISION"("REV") NOCHECK;   
ALTER TABLE "DN_AUD"."AUD_APPUSER" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."FKCO6B4BRN18Y5MIW81H8YQJC1W" FOREIGN KEY("REV") REFERENCES "DN_AUD"."AUD_REVISION"("REV") NOCHECK;
ALTER TABLE "DN_AUD"."AUD_DRONE" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."FKHK4C11K9IDB7XQJOG22A53RYW" FOREIGN KEY("REV") REFERENCES "DN_AUD"."AUD_REVISION"("REV") NOCHECK;  
ALTER TABLE "DN_AUD"."AUD_APPROLE" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."FKRAPQ1333EN6ACGD57UDD1OWU" FOREIGN KEY("REV") REFERENCES "DN_AUD"."AUD_REVISION"("REV") NOCHECK; 
ALTER TABLE "DN_AUD"."AUD_LOAD" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."FKAAOH4J2VQ9RTLHMSR0Q3SF6I5" FOREIGN KEY("REV") REFERENCES "DN_AUD"."AUD_REVISION"("REV") NOCHECK;   
ALTER TABLE "DN_AUD"."AUD_ITEM" ADD CONSTRAINT IF NOT EXISTS "DN_AUD"."FKJDPVN68INY2G5C2LYQMR7DPKI" FOREIGN KEY("REV") REFERENCES "DN_AUD"."AUD_REVISION"("REV") NOCHECK;   
ALTER TABLE "DN_MAIN"."DM_DRONE" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FKCNDNRIBIXLGHYF6L79ULN5HJ4" FOREIGN KEY("MODEL_ID") REFERENCES "DN_DICT"."DF_LOAD_MODEL"("MODEL_ID") NOCHECK;     
ALTER TABLE "DN_MAIN"."DM_TRIP" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FK87JN59RT9RT7F8R0RO0GTPB57" FOREIGN KEY("OFFICE_ID") REFERENCES "DN_DICT"."DF_STATION"("STATION_ID") NOCHECK;      
ALTER TABLE "DN_MAIN"."DM_TRIP" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FK43HHXCK1FXWTFTUIEKRUXSQPW" FOREIGN KEY("DRONE_ID") REFERENCES "DN_MAIN"."DM_DRONE"("DRONE_ID") NOCHECK;           
ALTER TABLE "DN_MAIN"."DM_LOAD" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FKB2S1V97V95M6TSHWJYMKGRH8K" FOREIGN KEY("LOAD_TYPE_ID") REFERENCES "DN_DICT"."DF_LOAD_TYPE"("LOAD_TYPE_ID") NOCHECK;               
ALTER TABLE "DN_MAIN"."DM_TRIP" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FK13W9EKC6GWH0Y3KAH1WOSEAEY" FOREIGN KEY("STATUS_ID") REFERENCES "DN_DICT"."DF_TRIP_STATUS"("STATUS_ID") NOCHECK;   
ALTER TABLE "DN_MAIN"."DM_APPUSER" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FKIDIJUR1QPMPJU9O2YYPVXMJH2" FOREIGN KEY("ASSIGNEE_USER_ID") REFERENCES "DN_MAIN"."DM_APPUSER"("USER_ID") NOCHECK;               
ALTER TABLE "DN_MAIN"."DM_APPUSER" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FKEBBLLIO6YR24V6NX4YBLIF562" FOREIGN KEY("OFFICE_ID") REFERENCES "DN_DICT"."DF_OFFICE"("OFFICE_ID") NOCHECK;     
ALTER TABLE "DN_MAIN"."DM_USER_PERMISSION" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FKO9SFXNK93TEBF5KTFGOYNJRJ" FOREIGN KEY("ROLE_ID") REFERENCES "DN_MAIN"."DM_APPROLE"("ROLE_ID") NOCHECK; 
ALTER TABLE "DN_MAIN"."DM_USER_PERMISSION" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FK6RJATUXE7I1OC2KEYT1WPF39Y" FOREIGN KEY("USER_ID") REFERENCES "DN_MAIN"."DM_APPUSER"("USER_ID") NOCHECK;
ALTER TABLE "DN_MAIN"."DM_DRONE" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FKCY857UAR9L6S0TD0394Y3HTOA" FOREIGN KEY("STATE_ID") REFERENCES "DN_DICT"."DF_DRONE_STATE"("STATE_ID") NOCHECK;    
ALTER TABLE "DN_MAIN"."DM_TRIP" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FK6XV2WNPXAT01HDG444KJNKJHT" FOREIGN KEY("STATION_ID") REFERENCES "DN_DICT"."DF_STATION"("STATION_ID") NOCHECK;     
ALTER TABLE "DN_MAIN"."DM_LOAD" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FK5MC4Q45JISUGLMFIR2NVDSEC9" FOREIGN KEY("TRIP_ID") REFERENCES "DN_MAIN"."DM_TRIP"("TRIP_ID") NOCHECK;              
ALTER TABLE "DN_MAIN"."DM_ITEM" ADD CONSTRAINT IF NOT EXISTS "DN_MAIN"."FKFC6F0942PL4TL6WG834NKVD0C" FOREIGN KEY("LOAD_ID") REFERENCES "DN_MAIN"."DM_LOAD"("LOAD_ID") NOCHECK;              
